# Generated by Django 2.2.2 on 2019-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='default.svg', max_length=200),
        ),
    ]
